#!/bin/bash
# start db
#/usr/sbin/apache2ctl -D FOREGROUND & sleep 3



set -e
set -x
service apache2 restart & sleep 3


# first, if the /var/lib/mysql directory is empty, unpack it from our predefined db
[ "$(ls -A /var/lib/mysql)" ] && echo "Running with existing database in /var/lib/mysql" || ( echo 'Populate initial db'; tar xpzvf default_mysql.tar.gz )

if [ -S /var/run/mysqld/mysqld.sock ] ; then
echo 'remove sock'
            #rm /var/run/mysqld/mysqld.sock
rm /var/run/mysqld/mysqld.sock.lock
fi
/usr/sbin/mysqld



